version: '3.8'

services:
  # Backend - Spring Boot
  backend:
    build: ~/spring-boot-angular-17-postgresql-example/spring-boot-server
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  # Frontend - Angular
  frontend:
    build: ~/spring-boot-angular-17-postgresql-example/angular-17-client
    container_name: frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend

  # PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hw
    ports:
      - "5432:5432"
    volumes:
      - C:\miniapplication\postgres_data:/var/lib/postgressql/data

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  

